# Generated by Django 4.1.7 on 2023-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('do_date', models.DateTimeField(verbose_name='date when the note is worked on')),
                ('done_date', models.DateTimeField(verbose_name='date when the note is finished')),
                ('progress', models.IntegerField(default=0, verbose_name='note progress: 0 ToDo, 1 Doing, 2 Done')),
            ],
        ),
    ]
