# Generated by Django 4.1.7 on 2023-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(default='Here coud be your description!', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='do_date',
            field=models.DateTimeField(default=models.DateTimeField(verbose_name='date published'), verbose_name='date when the note is worked on'),
        ),
        migrations.AlterField(
            model_name='note',
            name='done_date',
            field=models.DateTimeField(default=models.DateTimeField(verbose_name='date published'), verbose_name='date when the note is finished'),
        ),
    ]
