# Generated by Django 4.1.7 on 2023-03-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_description_alter_note_do_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('day_started', models.IntegerField(default=0, verbose_name='number of notes day started with')),
                ('day_ended', models.IntegerField(default=0, verbose_name='number of notes day ended with')),
                ('progress', models.IntegerField(default=0, verbose_name='day progress')),
            ],
        ),
    ]
