# Generated by Django 4.1.7 on 2023-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_colorgrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='do_date',
            field=models.DateField(default=models.DateField(verbose_name='date published'), verbose_name='date when the note is worked on'),
        ),
        migrations.AlterField(
            model_name='note',
            name='done_date',
            field=models.DateField(default=models.DateField(verbose_name='date published'), verbose_name='date when the note is finished'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
