# Generated by Django 4.1.7 on 2023-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_do_date_alter_note_done_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorgrid',
            name='day_has_started',
            field=models.BooleanField(default=False),
        ),
    ]
