# Generated by Django 4.1.7 on 2023-04-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_colorgrid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='note has already be counted as done note for the color grid'),
        ),
    ]
